### PR TITLE
More extensions from dapper

### PR DESCRIPTION
**Pull request by carl-berg**
Added support for Single and SingleOrDefault extensions, those are ones i've been missing.
Two other questions:
- No support for sync-stuff (i have sometimes needed/wanted this)
- No support for dynamic (i have not yet needed this)

### CODE REVIEW

**Comment by mattiasnordqvist** [comment]
We could do sync, maybe in another Extensions-class to avoid too many autocompletion-alternatives in vs.
How ~~do~~ would you use dynamic?

**Comment by carl-berg** [comment]
I dont' use dynamic. Just noticed that dapper supports it 😸

**Comment by mattiasnordqvist** [comment]
Like... dynamic for parameters?

**Comment by carl-berg** [comment]
Dynamic return types, like https://github.com/StackExchange/Dapper/blob/master/Dapper/SqlMapper.cs#L662

**Review by mattiasnordqvist — APPROVED** [review]

**Comment by mattiasnordqvist** [comment]
released in JellyDust.Dapper v0.0.8.1

**Pull request merged**
